# Generated by Django 4.1.7 on 2023-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.CharField(max_length=500)),
                ('imgpath', models.CharField(max_length=50)),
            ],
        ),
    ]
